export const formData = {
  formSelector: ".form",
  inputSelector: ".form__input",
  submitButtonSelector: ".form__submit",
  editFormId: "#edit",
  cardFormId: "#card",
  avatarFormId: "#avatar",
  nameId: "#edit-name",
  descriptionId: "#edit-about",
  titleId: "#card-title",
  linkId: "#card-link",
  avatarId: "#avatar-link",
  inactiveButtonClass: "form__submit_inactive",
  inputErrorClass: "form__input_type_error",
  errorVisibleClass: "form__error_visible",
};
